### ISSUE TITLE
Sum Reduction Process

### ISSUE THREAD

**Issue by Panxuran** [moabarar/qna#8] opened 2022-06-23 08:15 UTC
Hi! Great work and thanks for sharing the code!

I have a little concern about the sum reduction process (i.e., the **Sum_k** in Appendix). My understanding is that the sum reduction operation is conducted based on convolution functions with carefully designed kernel weights. I wonder if this is considered in the total computation FLOPs of the whole model?

**Comment by moabarar** [comment] 2022-06-24 12:39
Thank you for your interest in our work - I am glad you liked it. 

Regarding the FLOPs, I have computed the flops using analysis reported by XLA compiler on the computation graph. My code was based on the implementation of Nested Transformer:
https://github.com/google-research/nested-transformer/blob/main/libml/utils.py

Please also note, that we use **Grouped convolution** to implement the layer,  this means the overhead caused by the usage of convolution is relatively small. 

Finally, the use of convolution may not be the most efficient way to implement QnA, and theoretically the flops should be smaller. More specifically, we need to use the Convolution implementation to support relative positional embedding, which are simply a bias term that is added to the softmax operand.

**Comment by Panxuran** [comment] 2022-06-29 09:58
Thanks for your timely response. I am sorry that I am not familiar with the XLA complier tool. Nevertheless, I suppose you mean the FLOPs for the group convolutions are alreadly included in the paper (e.g., 2.5G for QnA-Tiny) ?

By the way, I think the idea of using generalized convolution to perform local attention is really brilliant! Although it may involves additional cost, I believe it is still much more efficient than other local attention works. Thanks again for your great work!

**Comment by moabarar** [comment] 2022-06-30 08:09
Yes, The FLOPS include the grouped convolutions. 
And, I appreciate your comment on our work! 
I will be closing the issue - feel free to re-open if necessary.

**Closed as completed by moabarar** 2022-06-30 08:09 UTC
